### ISSUE TITLE
Switching sitemap doesn't work

### ISSUE THREAD

**Issue by idserda** [llamahunter/openhab.pebble#2]
On Pebble Time, switching sitemaps by holding down the Select button doesn't work. It shows the openHAB logo but nothing happens after this. This occurs with and without a default sitemap configured. I have several sitemap configured in openHAB. 

App version 1.0 (from app store)  
Watch software v3.0
Android 5.1.1, Nexus 5

**Comment by llamahunter** [comment]
Hmm. I did have to fix a bug in OpenHAB itself around sitemap listings. Do you have an up to date version?

**Comment by idserda** [comment]
I'm on a 1.8-SNAPSHOT build. If there's no default sitemap configured the listing works fine when opening the app.

**Comment by llamahunter** [comment]
Can you make sure you have this change in your tree https://github.com/openhab/openhab/pull/2512  However, that pull request is 6 months old, so almost certainly is in 1.8.

FWIW, it 'works for me' using a default sitemap, but I'm on iOS.  Not clear how the phone version would matter, but they do likely have slightly different web browser libraries.  Any chance you could get some logs?

**Comment by idserda** [comment]
From the logs: 

```
[PHONE] pebble-app.js:?: OpenHAB:1083 JavaScript Error:
TypeError: window.hide is not a function
    at Object.exports.popAll (windowmgr.js:42:12)
    at resetSitemap (sitemap.js:27:13)
    at null.<anonymous> (page.js:206:5)
    at emitToHandlers (lib/emitter.js:121:17)
    at Emitter.emit (lib/emitter.js:145:31)
    at Window._emit (ui/window.js:274:12)
    at Function.Window.emit (ui/window.js:286:17)
    at Function.Menu.emitSelect (ui/menu.js:355:12)
    at Object.SimplyPebble.onPacket (ui/simply-pebble.js:1260:12)
    at Array.SimplyPebble.onAppMessage (ui/simply-pebble.js:1279:18)
```

window object: 

```
{
  "document": {
    "location": {
      "hash": "",
      "search": "?params={"loadUrl":"/data/data/com.getpebble.android.basalt/app_js_app_files/73ad05b2-2f62-4f57-934a-0f820530f401/pebble-js-app.js"}",
      "pathname": "/android_asset/webview_startup.html",
      "port": "",
      "hostname": "",
      "host": "",
      "protocol": "file:",
      "origin": "file://",
      "href": "file:///android_asset/webview_startup.html?params={"loadUrl":"/data/data/com.getpebble.android.basalt/app_js_app_files/73ad05b2-2f62-4f57-934a-0f820530f401/pebble-js-app.js"}",
      "ancestorOrigins": {}
    }
  },
  "Pebble": {
    "showSimpleNotificationOnPebble": "[Unknown]",
    "showToast": "[Unknown]"
  },
  "_Pebble": "[Unknown]",
  "sDefaultTimeout": "[Unknown]",
  "newSend": "[Unknown]",
  "newOpen": "[Unknown]",
  "overridenGetCurrentPosition": "[Unknown]",
  "isFunction": "[Unknown]",
  "PebbleEventListener": "[Unknown]",
  "signalWebviewOpenedEvent": "[Unknown]",
  "signalReady": "[Unknown]",
  "signalWebviewClosedEvent": "[Unknown]",
  "signalNewAppMessageData": "[Unknown]",
  "signalAppMessageAck": "[Unknown]",
  "signalAppMessageNack": "[Unknown]",
  "removeAppMessageCallbacksForTransactionId": "[Unknown]",
  "signalSettingsWebuiLaunchOpportunity": "[Unknown]",
  "_initLocalStorageMonitor": "[Unknown]",
  "signalLoaded": "[Unknown]",
  "signalBodyLoaded": "[Unknown]",
  "loadScript": "[Unknown]",
  "loadBody": "[Unknown]",
  "httpGetNativeJsSynchro": "[Unknown]",
  "scriptHasEmbeddedAppInfo": "[Unknown]",
  "pingWebcontext": "[Unknown]",
  "getTimelineSubscribeToTopicURL": "[Unknown]",
  "getTimelineSubscriptionsListURL": "[Unknown]",
  "signalTimelineTokenSuccess": "[Unknown]",
  "signalTimelineTokenFailure": "[Unknown]",
  "_appMessageAckCallbacks": "[Unknown]",
  "_appMessageNackCallbacks": "[Unknown]",
  "__loader": "[Unknown]",
  "DecodeStream": "[Unknown]",
  "FlateStream": "[Unknown]",
  "moment": "[Unknown]",
  "PNG": "[Unknown]",
  "setTimeout": "[Unknown]",
  "setInterval": "[Unknown]",
  "sitemap": "[Unknown]",
  "widget": "[Unknown]",
  "subwidget": "[Unknown]",
  "mapping": "[Unknown]",
  "caches": "[Unknown]",
  "localStorage": "[Unknown]",
  "sessionStorage": "[Unknown]",
  "webkitStorageInfo": "[Unknown]",
  "indexedDB": "[Unknown]",
  "webkitIndexedDB": "[Unknown]",
  "crypto": "[Unknown]",
  "orientation": "[Unknown]",
  "applicationCache": "[Unknown]",
  "performance": "[Unknown]",
  "styleMedia": "[Unknown]",
  "defaultstatus": "[Unknown]",
  "defaultStatus": "[Unknown]",
  "screenTop": "[Unknown]",
  "screenLeft": "[Unknown]",
  "clientInformation": "[Unknown]",
  "console": "[Unknown]",
  "devicePixelRatio": "[Unknown]",
  "outerHeight": "[Unknown]",
  "outerWidth": "[Unknown]",
  "screenY": "[Unknown]",
  "screenX": "[Unknown]",
  "pageYOffset": "[Unknown]",
  "scrollY": "[Unknown]",
  "pageXOffset": "[Unknown]",
  "scrollX": "[Unknown]",
  "innerHeight": "[Unknown]",
  "innerWidth": "[Unknown]",
  "screen": "[Unknown]",
  "navigator": "[Unknown]",
  "frameElement": "[Unknown]",
  "parent": "[Circular]",
  "opener": "[Unknown]",
  "top": "[Circular]",
  "length": "[Unknown]",
  "frames": "[Circular]",
  "closed": "[Unknown]",
  "status": "[Unknown]",
  "toolbar": "[Unknown]",
  "statusbar": "[Unknown]",
  "scrollbars": "[Unknown]",
  "personalbar": "[Unknown]",
  "menubar": "[Unknown]",
  "locationbar": "[Unknown]",
  "history": "[Unknown]",
  "location": "[Unknown]",
  "name": "[Unknown]",
  "self": "[Circular]",
  "window": "[Circular]"
}
```
